### ISSUE TITLE
printCrudeAndAdjustedModel gives error when only using two levels

### ISSUE THREAD

**Issue by raubreywhite** [gforge/Greg#5]
Issue 1. It looks as though printCrudeAndAdjustedModel needs at least 3 levels when using "desc_column=TRUE". So when sex (m/f) has no missing (thus only 2 levels), it will give an error. When sex (m/f) has missing (thus, three levels=m/f/NA), it works fine.

Issue 2. Is there a way to get "desc_column" to only show the number of observations actually used in the analysis? When a person has a lot of missing data and does a complete case analysis, the desc_column becomes really uninformative.

Otherwise, thank you for an amazing package!! It has been so useful!

library(Gmisc)
library(Greg)
library(Hmisc)
library(htmlTable)
data <- data.frame(outcome=rnorm(100),sex=sample(c("Male","Female"),100,TRUE),country=sample(c("USA","UK","AUS"),100,TRUE))

data$sex <- factor(data$sex,levels=c("Male","Female"))
data$country <- factor(data$country,levels=c("USA","UK","AUS"))

fit <- lm(outcome ~ sex + country, data=data)
printCrudeAndAdjustedModel(fit,desc_column=TRUE)

data$sex[1] <- NA
printCrudeAndAdjustedModel(fit,desc_column=TRUE)

**Comment by gforge** [comment]
Thanks!

Issue 1: Fixed in 1.0.4 - minor note, data.frame automatically converts character vectors to factors and if you have a character vector that you want to convert to a factor then you don't need to specify the levels unless there are some levels not present in the current set.

Issue 2: This seems like poor practice since imputation probably should be your first choice. If you still want to remove missing then create a new data.frame with na.omit() in the stats package.
